version: '3'
services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/page02/
    volumes:
      - type: bind
        source: "./web"
        target: "/var/www/html"
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./mariadb/data"
        target: "/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      # MySQLのイメージを使用するなら、環境変数は「MYSQL_ROOT_PASSWORD」に。
      - MARIADB_ROOT_PASSWORD=myrootpassword
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"